<?php

use Illuminate\Database\Seeder;

class ArtSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arts = [
            array('Id' => '1','Art' => 'VisualArts','Level' => '1','Parentid' => '0'),
            array('Id' => '2','Art' => 'Painting','Level' => '2','Parentid' => '1'),
            array('Id' => '3','Art' => 'Cartooning','Level' => '2','Parentid' => '1'),
            array('Id' => '4','Art' => 'Graffitti','Level' => '2','Parentid' => '1'),
            array('Id' => '5','Art' => 'Sculpture','Level' => '2','Parentid' => '1'),
            array('Id' => '6','Art' => 'Animation','Level' => '2','Parentid' => '1'),
            array('Id' => '7','Art' => 'Digital','Level' => '2','Parentid' => '1'),
            array('Id' => '8','Art' => 'Concept','Level' => '2','Parentid' => '1'),
            array('Id' => '9','Art' => 'Origami','Level' => '2','Parentid' => '1'),
            array('Id' => '10','Art' => 'Fashion','Level' => '2','Parentid' => '1'),
            array('Id' => '11','Art' => 'InteriorDesign','Level' => '2','Parentid' => '1'),
            array('Id' => '12','Art' => 'Installation','Level' => '2','Parentid' => '1'),
            array('Id' => '13','Art' => 'Glass','Level' => '2','Parentid' => '1'),
            array('Id' => '14','Art' => 'Ceramics','Level' => '2','Parentid' => '1'),
            array('Id' => '15','Art' => 'Tatooing','Level' => '2','Parentid' => '1'),
            array('Id' => '16','Art' => 'Teacher','Level' => '2','Parentid' => '1'),
            array('Id' => '17','Art' => 'Dance','Level' => '1','Parentid' => '0'),
            array('Id' => '18','Art' => 'Ballet','Level' => '2','Parentid' => '17'),
            array('Id' => '19','Art' => 'Breakdancing','Level' => '2','Parentid' => '17'),
            array('Id' => '20','Art' => 'Poplock','Level' => '2','Parentid' => '17'),
            array('Id' => '21','Art' => 'Ballroom','Level' => '2','Parentid' => '17'),
            array('Id' => '22','Art' => 'Jazz','Level' => '2','Parentid' => '17'),
            array('Id' => '23','Art' => 'Tap','Level' => '2','Parentid' => '17'),
            array('Id' => '24','Art' => 'Bellydancing','Level' => '2','Parentid' => '17'),
            array('Id' => '25','Art' => 'Instructor','Level' => '2','Parentid' => '17'),
            array('Id' => '26','Art' => 'Music','Level' => '1','Parentid' => '0'),
            array('Id' => '27','Art' => 'Singer','Level' => '2','Parentid' => '26'),
            array('Id' => '28','Art' => 'Rapper','Level' => '2','Parentid' => '26'),
            array('Id' => '29','Art' => 'Guitar','Level' => '2','Parentid' => '26'),
            array('Id' => '30','Art' => 'Drums','Level' => '2','Parentid' => '26'),
            array('Id' => '31','Art' => 'Violin','Level' => '2','Parentid' => '26'),
            array('Id' => '32','Art' => 'Piano','Level' => '2','Parentid' => '26'),
            array('Id' => '33','Art' => 'DJ','Level' => '2','Parentid' => '26'),
            array('Id' => '34','Art' => 'Composer','Level' => '2','Parentid' => '26'),
            array('Id' => '35','Art' => 'Historian','Level' => '2','Parentid' => '26'),
            array('Id' => '36','Art' => 'Producer','Level' => '2','Parentid' => '26'),
            array('Id' => '37','Art' => 'Writing','Level' => '1','Parentid' => '0'),
            array('Id' => '38','Art' => 'Fiction','Level' => '2','Parentid' => '37'),
            array('Id' => '39','Art' => 'NonFiction','Level' => '2','Parentid' => '37'),
            array('Id' => '40','Art' => 'Screenwriter','Level' => '2','Parentid' => '37'),
            array('Id' => '41','Art' => 'PlayWriter','Level' => '2','Parentid' => '37'),
            array('Id' => '42','Art' => 'SongWriter','Level' => '2','Parentid' => '37'),
            array('Id' => '43','Art' => 'Freelance','Level' => '2','Parentid' => '37'),
            array('Id' => '44','Art' => 'Poetry','Level' => '2','Parentid' => '37'),
            array('Id' => '45','Art' => 'Journalist','Level' => '2','Parentid' => '37'),
            array('Id' => '46','Art' => 'Humor','Level' => '2','Parentid' => '37'),
            array('Id' => '47','Art' => 'SpeechWriter','Level' => '2','Parentid' => '37'),
            array('Id' => '48','Art' => 'Publisher','Level' => '2','Parentid' => '37'),
            array('Id' => '49','Art' => 'Editor','Level' => '2','Parentid' => '37'),
            array('Id' => '50','Art' => 'Culinary','Level' => '1','Parentid' => '0'),
            array('Id' => '51','Art' => 'Baker','Level' => '2','Parentid' => '50'),
            array('Id' => '52','Art' => 'ExecutiveChef','Level' => '2','Parentid' => '50'),
            array('Id' => '53','Art' => 'PersonalChef','Level' => '2','Parentid' => '50'),
            array('Id' => '54','Art' => 'PastryChef','Level' => '2','Parentid' => '50'),
            array('Id' => '55','Art' => 'RestaurantManager','Level' => '2','Parentid' => '50'),
            array('Id' => '56','Art' => 'PerformingArts','Level' => '1','Parentid' => '0'),
            array('Id' => '57','Art' => 'Actor','Level' => '2','Parentid' => '56'),
            array('Id' => '58','Art' => 'Director','Level' => '2','Parentid' => '56'),
            array('Id' => '59','Art' => 'Theatre','Level' => '2','Parentid' => '56'),
            array('Id' => '60','Art' => 'Comedian','Level' => '2','Parentid' => '56'),
            array('Id' => '61','Art' => 'Entrepreneurship','Level' => '1','Parentid' => '0'),
            array('Id' => '62','Art' => 'Investor','Level' => '2','Parentid' => '61'),
            array('Id' => '63','Art' => 'CEO','Level' => '2','Parentid' => '61'),
            array('Id' => '64','Art' => 'PublicRelations','Level' => '2','Parentid' => '61'),
            array('Id' => '65','Art' => 'Marketing','Level' => '2','Parentid' => '61'),
            array('Id' => '66','Art' => 'Franchiser','Level' => '2','Parentid' => '61'),
            array('Id' => '67','Art' => 'Franshisee','Level' => '2','Parentid' => '61'),
            array('Id' => '68','Art' => 'Product','Level' => '2','Parentid' => '61'),
            array('Id' => '69','Art' => 'Service','Level' => '2','Parentid' => '61'),
            array('Id' => '70','Art' => 'Sports','Level' => '1','Parentid' => '0'),
            array('Id' => '71','Art' => 'Basketball','Level' => '2','Parentid' => '70'),
            array('Id' => '72','Art' => 'Gymnastics','Level' => '2','Parentid' => '70'),
            array('Id' => '73','Art' => 'Soccer','Level' => '2','Parentid' => '70'),
            array('Id' => '74','Art' => 'Football','Level' => '2','Parentid' => '70'),
            array('Id' => '75','Art' => 'BodyBuilding','Level' => '2','Parentid' => '70'),
            array('Id' => '76','Art' => 'Track&Field','Level' => '2','Parentid' => '70'),
            array('Id' => '77','Art' => 'Baseball','Level' => '2','Parentid' => '70'),
            array('Id' => '78','Art' => 'Archery','Level' => '2','Parentid' => '70'),
            array('Id' => '79','Art' => 'Tennis','Level' => '2','Parentid' => '70'),
            array('Id' => '80','Art' => 'Boxing','Level' => '2','Parentid' => '70'),
            array('Id' => '81','Art' => 'Parkour','Level' => '2','Parentid' => '70'),
            array('Id' => '82','Art' => 'CarRacing','Level' => '2','Parentid' => '70'),
            array('Id' => '83','Art' => 'Coach','Level' => '2','Parentid' => '70'),
            array('Id' => '84','Art' => 'MartialArts','Level' => '1','Parentid' => '0'),
            array('Id' => '85','Art' => 'Wushu','Level' => '2','Parentid' => '84'),
            array('Id' => '86','Art' => 'Karate','Level' => '2','Parentid' => '84'),
            array('Id' => '87','Art' => 'Aikido','Level' => '2','Parentid' => '84'),
            array('Id' => '88','Art' => 'Judo','Level' => '2','Parentid' => '84'),
            array('Id' => '89','Art' => 'Kendo','Level' => '2','Parentid' => '84'),
            array('Id' => '90','Art' => 'JiuJitsu','Level' => '2','Parentid' => '84'),
            array('Id' => '91','Art' => 'TaiChi','Level' => '2','Parentid' => '84'),
            array('Id' => '92','Art' => 'Goju','Level' => '2','Parentid' => '84'),
            array('Id' => '93','Art' => 'Kali','Level' => '2','Parentid' => '84'),
            array('Id' => '94','Art' => 'WingChun','Level' => '2','Parentid' => '84'),
            array('Id' => '95','Art' => 'Capoeira','Level' => '2','Parentid' => '84'),
            array('Id' => '96','Art' => 'Sensei','Level' => '2','Parentid' => '84'),
            array('Id' => '97','Art' => 'Sifu','Level' => '2','Parentid' => '84'),
            array('Id' => '98','Art' => 'Mestre','Level' => '2','Parentid' => '84'),
            array('Id' => '99','Art' => 'TaeKwonDo','Level' => '2','Parentid' => '84'),
            array('Id' => '100','Art' => 'Ninjitsu','Level' => '2','Parentid' => '84'),
            array('Id' => '101','Art' => 'Cosplay','Level' => '1','Parentid' => '0'),
            array('Id' => '102','Art' => 'PublicSpeaking','Level' => '1','Parentid' => '0'),
            array('Id' => '103','Art' => 'Motivational','Level' => '2','Parentid' => '102'),
            array('Id' => '104','Art' => 'Entertaining','Level' => '2','Parentid' => '102'),
            array('Id' => '105','Art' => 'Informational','Level' => '2','Parentid' => '102'),
            array('Id' => '106','Art' => 'Debate','Level' => '2','Parentid' => '102'),
            array('Id' => '107','Art' => 'Toastmasters','Level' => '2','Parentid' => '102'),
            array('Id' => '108','Art' => 'Inspirational','Level' => '2','Parentid' => '102'),
            array('Id' => '109','Art' => 'Professional','Level' => '2','Parentid' => '102'),
            array('Id' => '110','Art' => 'Persuasive','Level' => '2','Parentid' => '102'),
            array('Id' => '111','Art' => 'Activist','Level' => '2','Parentid' => '102'),
            array('Id' => '117','Art' => 'WebDesign','Level' => '1','Parentid' => '0'),
            array('Id' => '118','Art' => 'Programmer','Level' => '2','Parentid' => '117'),
            array('Id' => '119','Art' => 'new','Level' => '2','Parentid' => '101'),
            array('Id' => '120','Art' => 'bfgfgfdg','Level' => '1','Parentid' => '0'),
            array('Id' => '121','Art' => 'test','Level' => '2','Parentid' => '120')
        ];

        foreach ($arts as $art) {
            DB::table('arts')->insert([
                'id' => $art['Id'],
                'parent_id' => $art['Parentid'] == 0 ? null : $art['Parentid'],
                'name'=> $art['Art']
            ]);
        }
    }
}
