version: '3'
services:

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mezum_laravel
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_test
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  #phpmyadmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_test
    ports:
      - "8080:80"
    depends_on:
      - db
    links: 
      - db
    networks:
      - app-network

  meuzm:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_USERNAME: "root"
      DB_PASSWORD: "root_test"
      DB_PORT: "3306"
      DB_DATABASE: "mezum_laravel"
    ports:
      - "8001:8000"
    depends_on:
      - db
    links: 
      - db
    networks:
      - app-network
  meuzm-node: 
    build: 
      context: ../nodeApp/
      dockerfile: Dockerfile
    environment: 
      FRONT_APP_URL: "https://staging.meuzm.com/"
      BACKEND_APP_URL: "https://staging-api.meuzm.com/api/v1/"
      NODE_APP_ENV: local
      NODE_APP_PORT: "8030"
    ports:
      - "8030:8080"
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local