name: Laravel

on:
  push:
    branches: [ develop ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - name: Connect
      run: |
        eval `ssh-agent`
        ssh-add - <<< "${{ secrets.SSH_KEY }}"
        ssh -tt ubuntu@184.169.228.69
        cd /home/ubuntu/meuzmnet-laravel
        /usr/bin/git pull origin develop
